export const TractorParcelError = {
  INVALID_ID: 'INVALID_ID',
  INVALID_TRACTOR_ID: 'INVALID_TRACTOR_ID',
  INVALID_PARCEL_ID: 'INVALID_PARCEL_ID',
  OUT_OF_RANGE: 'OUT_OF_RANGE',
  ALREADY_PROCESSED: 'ALREADY_PROCESSED',
};
